name: 'Covid-19 no Brasil: Análises, gráficos e projeções a partir de dados históricos.'
description: Converts Jupyter notebooks and Word docs into Jekyll blog posts.
author: Fernando Wittmann & Vinicius Bastos Gomes
inputs:
  BOOL_SAVE_MARKDOWN:
    description: Either 'true' or 'false'.  Whether or not to commit converted markdown files from notebooks and word documents into the _posts directory in your repo.  This is useful for debugging.
    required: false
    default: false
  SSH_DEPLOY_KEY:
    description: a ssh deploy key is required if BOOL_SAVE_MARKDOWN = 'true'
    required: false
branding:
  color: 'blue'
  icon: 'book'
runs:
  using: 'docker'
  image: 'Dockerfile'
